# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63b16e51ddcfcadb407c9baef0f00c9e5f97a57e07d681bebc51be58a142f9e1473e5aba92a26b7185173899c4034dce807f9d239a17a8c710cbdc6786154e9c

test:
  secret_key_base: 83eb1e69f755152ffaf2a69327a75deec4d107fcc4ef3be8d6ec824bcf3868f43e36e4777ec43735cb57a47a3d1d92acea2fe348a7aa4442d2fabd1a83df30de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
